INSERT INTO Programateur(nomProgramateur) VALUES ('UGC DIFFUSION');
INSERT INTO Programateur(nomProgramateur) VALUES ('SA MK2 VISION');
INSERT INTO Programateur(nomProgramateur) VALUES ('SNC SAGEC - CINE 32 VEO');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL MC4 DISTRIBUTION');
INSERT INTO Programateur(nomProgramateur) VALUES ('LES CINEMAS GAUMONT PATHE');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL LES FILMS DE LA ROCHELLE');
INSERT INTO Programateur(nomProgramateur) VALUES ('SAS CINE DIFFUSION');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL MICROMEGAS DIFFUSION CINEMATOGRAPHIQUE');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL MULTICINES PYRENNEENS (Xavier-Menou)');
INSERT INTO Programateur(nomProgramateur) VALUES ('CINEMAGINAIRE');
INSERT INTO Programateur(nomProgramateur) VALUES ('ENT. REG. CIN. NORD PAS DE CALAIS');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL GPCI');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL NORD OUEST EXPLOITATION CINEMA');
INSERT INTO Programateur(nomProgramateur) VALUES ('SOGECI');
INSERT INTO Programateur(nomProgramateur) VALUES ('SUD CINE');
INSERT INTO Programateur(nomProgramateur) VALUES ('ARTEC');
INSERT INTO Programateur(nomProgramateur) VALUES ('UGC MEDITERRANEE');
INSERT INTO Programateur(nomProgramateur) VALUES ('SOGECIS');
INSERT INTO Programateur(nomProgramateur) VALUES ('GROUPEMENT DES SALLES FAMILIALES DE LYON (GSF)');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL CINEODE');
INSERT INTO Programateur(nomProgramateur) VALUES ('STE NOUVELLE DES CINEMAS DE DREUX (Brunet)');
INSERT INTO Programateur(nomProgramateur) VALUES ('SEM DU PALACE EPINAL (Toussaint)');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL CINEPROFILMS');
INSERT INTO Programateur(nomProgramateur) VALUES ('SAS AGORA CINEMAS');
INSERT INTO Programateur(nomProgramateur) VALUES ('PROVENCAUX ASSOCIES');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL EXHANTHUS');
INSERT INTO Programateur(nomProgramateur) VALUES ('CVL');
INSERT INTO Programateur(nomProgramateur) VALUES ('SAINT LOUIS');
INSERT INTO Programateur(nomProgramateur) VALUES ('CINE LANDES');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL LE CLUB (Pfister)');
INSERT INTO Programateur(nomProgramateur) VALUES ('SAS CINE LEMAN (Baud)');
INSERT INTO Programateur(nomProgramateur) VALUES ('Les cinemas GAUMONT-PATHE');
INSERT INTO Programateur(nomProgramateur) VALUES ('SEGECIS');
INSERT INTO Programateur(nomProgramateur) VALUES ('OCINE');
INSERT INTO Programateur(nomProgramateur) VALUES ('KINEPOLIS');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL SOCIETE CADURCIENNE D''EXPLOITATION CINEMATOGRAPHIQUE');
INSERT INTO Programateur(nomProgramateur) VALUES ('CAP''CINEMA');
INSERT INTO Programateur(nomProgramateur) VALUES ('GENERIQUE');
INSERT INTO Programateur(nomProgramateur) VALUES ('SONHIR');
INSERT INTO Programateur(nomProgramateur) VALUES ('SAR LE CLUB (Pfister)');
INSERT INTO Programateur(nomProgramateur) VALUES ('BROUILLER - SNES');
INSERT INTO Programateur(nomProgramateur) VALUES ('CINEPARADIS');
INSERT INTO Programateur(nomProgramateur) VALUES ('SA CINEMA MEGAREX (Wernet)');
INSERT INTO Programateur(nomProgramateur) VALUES ('MAURIENNE');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL UNIPERSONNELLE CINEMA LES VARIETES');
INSERT INTO Programateur(nomProgramateur) VALUES ('SNES');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL CINE 70 (Turpin)');
INSERT INTO Programateur(nomProgramateur) VALUES ('SAS JFR (Roupioz)');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL LE PARIS (Bouquet)');
INSERT INTO Programateur(nomProgramateur) VALUES ('IMAGO');
INSERT INTO Programateur(nomProgramateur) VALUES ('STE D''EXPLOITATION GRAND ECRAN (FRIDMAN)');
INSERT INTO Programateur(nomProgramateur) VALUES ('CINEGYR CARNAC');
INSERT INTO Programateur(nomProgramateur) VALUES ('Nord Est Cin�ma (Thirriot)');
INSERT INTO Programateur(nomProgramateur) VALUES ('SARL CINE PARADIS (Reggiani)');
INSERT INTO Programateur(nomProgramateur) VALUES ('CINERGYR-CARNAC');
INSERT INTO Programateur(nomProgramateur) VALUES ('SAS CINE MONTBLANC (Baud)');
INSERT INTO Programateur(nomProgramateur) VALUES ('GAP');
INSERT INTO Programateur(nomProgramateur) VALUES ('GRAND ECRAN');
INSERT INTO Programateur(nomProgramateur) VALUES ('TUPIN');
INSERT INTO Programateur(nomProgramateur) VALUES ('Montereau Point Com (Aubry)');
INSERT INTO Programateur(nomProgramateur) VALUES ('BLN MAJESTIC (Lengrand)');
INSERT INTO Programateur(nomProgramateur) VALUES ('SAS D''EXPLOITATION DU PALACE (Laval�e)');
INSERT INTO Programateur(nomProgramateur) VALUES ('SAS CINEMA LE TREFLE (Letzugs)');
INSERT INTO Programateur(nomProgramateur) VALUES ('SA MAJESTIC (Turpin)');
INSERT INTO Programateur(nomProgramateur) VALUES ('SA Majestic Compiegne (Meunier)');
INSERT INTO Programateur(nomProgramateur) VALUES ('Grand �cran');
INSERT INTO Programateur(nomProgramateur) VALUES ('CINE 70 TUPIN');
INSERT INTO Programateur(nomProgramateur) VALUES ('SEGECI');
INSERT INTO Programateur(nomProgramateur) VALUES ('SAS CINEMA LE MAJESTIC (Baud)');
INSERT INTO Programateur(nomProgramateur) VALUES ('SAS CINEFORTIS (Lemonnier)');
INSERT INTO Programateur(nomProgramateur) VALUES ('STE NOUVELLE DES CINEMAS MELIES (Carpels)');
INSERT INTO Programateur(nomProgramateur) VALUES ('SAS CINE VILLAGE');
