INSERT INTO Region(region) VALUES ('Auvergne - Rhône-Alpes');
INSERT INTO Region(region) VALUES ('Bourgogne - Franche-Comté');
INSERT INTO Region(region) VALUES ('Bretagne');
INSERT INTO Region(region) VALUES ('Centre - Val-de-Loire');
INSERT INTO Region(region) VALUES ('Corse');
INSERT INTO Region(region) VALUES ('Grand-Est');
INSERT INTO Region(region) VALUES ('Hauts-de-France');
INSERT INTO Region(region) VALUES ('Ile-de-France');
INSERT INTO Region(region) VALUES ('Normandie');
INSERT INTO Region(region) VALUES ('Nouvelle Aquitaine');
INSERT INTO Region(region) VALUES ('Occitanie');
INSERT INTO Region(region) VALUES ('Pays de la Loire');
INSERT INTO Region(region) VALUES ('''Provence-Alpes-Côte-d''''Azur''');
INSERT INTO Region(region) VALUES ('Alsace');
INSERT INTO Region(region) VALUES ('Aquitaine');
INSERT INTO Region(region) VALUES ('Auvergne');
INSERT INTO Region(region) VALUES ('Basse-Normandie');
INSERT INTO Region(region) VALUES ('Bourgogne');
INSERT INTO Region(region) VALUES ('Centre');
INSERT INTO Region(region) VALUES ('Champagne-Ardenne');
INSERT INTO Region(region) VALUES ('Franche-Comté');
INSERT INTO Region(region) VALUES ('Haute-Normandie');
INSERT INTO Region(region) VALUES ('Languedoc-Roussillon');
INSERT INTO Region(region) VALUES ('Limousin');
INSERT INTO Region(region) VALUES ('Lorraine');
INSERT INTO Region(region) VALUES ('Midi-Pyrénées');
INSERT INTO Region(region) VALUES ('Nord-Pas-de-Calais');
INSERT INTO Region(region) VALUES ('Picardie');
INSERT INTO Region(region) VALUES ('Poitou-Charentes');
INSERT INTO Region(region) VALUES ('Rhône-Alpes');
