INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('47501','Agen');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('2A501','Ajaccio');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('81502','Albi');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('30501','Al�s');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('80601','Amiens');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('49701','Angers');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('16601','Angoul�me');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('74601','Annecy');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('552','Arles');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('59501','Armenti�res (partie fran�aise)');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('62502','Arras');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('754','Avignon');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('2B501','Bastia');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('751','Bayonne (partie fran�aise)');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('60501','Beauvais');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('555','Belfort');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('553','Bergerac');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('25602','Besan�on');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('752','B�thune');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('34501','B�ziers');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('41501','Blois');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('33701','Bordeaux');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('62503','Boulogne-sur-Mer');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('1501','Bourg-en-Bresse');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('18501','Bourges');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('38501','Bourgoin-Jallieu');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('29701','Brest');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('554','Brive-la-Gaillarde');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('14601','Caen');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('62504','Calais');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('81501','Castres');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('51501','Ch�lons-en-Champagne');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('71501','Chalon-sur-Sa�ne');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('73601','Chamb�ry');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('8501','Charleville-M�zi�res');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('28501','Chartres');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('36501','Ch�teauroux');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('50501','Cherbourg-Octeville');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('49501','Cholet');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('63701','Clermont-Ferrand');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('74502','Cluses');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('68501','Colmar');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('60502','Compi�gne');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('60601','Creil');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('21701','Dijon');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('756','Douai - Lens');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('83501','Draguignan');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('59602','Dunkerque');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('88501','�pinal');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('27501','�vreux');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('83502','Fr�jus');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('652','Gen�ve (SUI) - Annemasse (partie fran�aise)');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('38701','Grenoble');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('67501','Haguenau');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('17601','La Rochelle');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('85501','La Roche-sur-Yon');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('33501','La Teste-de-Buch - Arcachon');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('53501','Laval');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('76701','Le Havre');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('72701','Le Mans');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('59702','Lille (partie fran�aise)');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('87601','Limoges');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('56601','Lorient');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('758','Lyon');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('759','Marseille - Aix-en-Provence');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('59601','Maubeuge (partie fran�aise)');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('77501','Meaux');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('6501','Menton - Monaco (partie fran�aise)');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('57701','Metz');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('45501','Montargis');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('82501','Montauban');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('25601','Montb�liard');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('551','Mont�limar');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('3501','Montlu�on');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('34701','Montpellier');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('68701','Mulhouse');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('54701','Nancy');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('44701','Nantes');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('11502','Narbonne');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('58501','Nevers');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('6701','Nice');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('30601','N�mes');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('79501','Niort');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('45701','Orl�ans');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('851','Paris');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('64601','Pau');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('24501','P�rigueux');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('66601','Perpignan');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('86601','Poitiers');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('29501','Quimper');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('51701','Reims');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('35701','Rennes');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('42502','Roanne');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('12402','Rodez');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('26501','Romans-sur-Is�re');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('755','Rouen');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('22501','Saint-Brieuc');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('66401','Saint-Cyprien');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('753','Saint-�tienne');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('42501','Saint-Just-Saint-Rambert');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('44601','Saint-Nazaire');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('62501','Saint-Omer');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('2501','Saint-Quentin');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('13501','Salon-de-Provence');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('57501','Sarrebruck (ALL) - Forbach (partie fran�aise)');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('34502','S�te');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('67701','Strasbourg (partie fran�aise)');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('65501','Tarbes');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('57601','Thionville');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('74501','Thonon-les-Bains');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('757','Toulon');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('31701','Toulouse');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('37701','Tours');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('10601','Troyes');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('651','Valence');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('59701','Valenciennes (partie fran�aise)');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('56501','Vannes');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('3502','Vichy');
INSERT INTO UniteUrbaine(numUniteUrbaine,nomUniteUrbaine) VALUES ('556','Vienne');
